title: John Doe # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  
  <a href="https://www.linkedin.com/in/andrew-schachter/">LinkedIn</a> 
  <br>
  <a href="/pdf/Andrew Schachter - Resume.pdf" class="btn btn--info">Portfolio</a>  
  <br>
  <a href="https://github.com/andrewschac">GitHub</a>  
  <br>
  
  
theme: jekyll-theme-minimal
